---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance_centos
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  # - name: instance_debian
  #   image: debian:stretch
  #   command: /sbin/init
  #   security_opts:
  #     - seccomp=path/to/seccomp.json
  #   tmpfs:
  #     - /run
  #     - /tmp
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
