---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance_ubuntu1804
    image: jrei/systemd-ubuntu:18.04
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: instance_ubuntu2004
    image: jrei/systemd-ubuntu:20.04
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
