---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance_debian9
    image: jrei/systemd-debian:9
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: instance_debian10
    image: jrei/systemd-debian:10
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
